app:
    controllerMap:
        scrutinizer:
            __class: hidev\scrutinizer\console\ScrutinizerController
        .scrutinizer.yml:
            __class: hidev\scrutinizer\console\ScrutinizerYamlController

scrutinizer:
    __class: hidev\scrutinizer\components\Scrutinizer
.scrutinizer.yml:
    __class: hidev\scrutinizer\components\ScrutinizerYaml

readme:
    knownBadges:
        scrutinizer.coverage:   '[![Scrutinizer Code Coverage](https://img.shields.io/scrutinizer/coverage/g/{{ app.github.full_name }}.svg)](https://scrutinizer-ci.com/g/{{ app.github.full_name }}/)'
        scrutinizer.quality:    '[![Scrutinizer Code Quality](https://img.shields.io/scrutinizer/g/{{ app.github.full_name }}.svg)](https://scrutinizer-ci.com/g/{{ app.github.full_name }}/)'
        scrutinizer.build:      '[![Scrutinizer Build Status](https://img.shields.io/scrutinizer/build/g/{{ app.github.full_name }}.svg)](https://scrutinizer-ci.com/g/{{ app.github.full_name }}/build-status/master)'

binaries:
    python-ocular:
        __class:    hidev\base\BinaryPython
        name:       ocular
        package:    scrutinizer-ocular
    php-ocular:
        __class:    hidev\base\BinaryPhp
        name:       ocular
        download:   https://scrutinizer-ci.com/ocular.phar
